export type PluginName = "german" | "running" | "stretching" | string;

export interface TodayTask {
  id: string;
  eventName: string;
  plugin: PluginName;
  type: string;
  summary: string;
  details: string[];
  fullSession: string[];
}

export interface ApiTaskPayload {
  type: string;
  summary?: string;
  sentences?: string[];
  notes?: string[];
  workout?: string;
  session_plan?: string[];
}

export interface ApiTodayTask {
  event_id: string;
  event_name: string;
  plugin: PluginName;
  task: ApiTaskPayload;
}

export interface ApiTodayResponse {
  date: string;
  tasks: ApiTodayTask[];
}

interface DailyVariants {
  german: string[];
  running: string[];
  stretching: string[];
}

export function mapTodayResponseToTasks(response: ApiTodayResponse): TodayTask[] {
  return response.tasks.map((item) => {
    const detailCandidates = [item.task.sentences, item.task.notes].filter(
      (value): value is string[] => Array.isArray(value),
    );

    const details = detailCandidates.flat();
    const fullSession =
      item.task.session_plan && item.task.session_plan.length > 0
        ? item.task.session_plan
        : details;

    const summary =
      item.task.summary ??
      item.task.workout ??
      details[0] ??
      `${item.event_name} task generated by ${item.plugin}`;

    return {
      id: item.event_id,
      eventName: item.event_name,
      plugin: item.plugin,
      type: item.task.type,
      summary,
      details,
      fullSession,
    };
  });
}

const dailyVariants: DailyVariants = {
  german: [
    "Speak 5 core phrases out loud",
    "Watch a 7-minute German video and repeat sentences",
    "Practice 10 travel phrases with pronunciation",
  ],
  running: [
    "Easy run 25 minutes with 5-minute warmup",
    "Intervals: 6 x 2 minutes fast / 2 minutes easy",
    "Recovery jog 20 minutes and 3 short strides",
  ],
  stretching: [
    "12-minute full body mobility sequence",
    "Hamstrings and hips focus, 10 minutes",
    "Upper-back and shoulders stretch, 12 minutes",
  ],
};

export function getMockTodayResponseForDate(date: Date): ApiTodayResponse {
  const dayIndex = date.getDate() % 3;

  return {
    date: date.toISOString().slice(0, 10),
    tasks: [
      {
        event_id: "german-daily",
        event_name: "German Practice",
        plugin: "german",
        task: {
          type: "speak",
          summary: dailyVariants.german[dayIndex],
          sentences: ["Ich heiße Boaz", "Ich komme aus Israel", "Ich lerne Deutsch"],
          session_plan: [
            "Warm up: read yesterday's 5 phrases once",
            "Listen to pronunciation for 3 minutes",
            "Speak today's 5 phrases out loud 3 rounds",
            "Record yourself for 60 seconds",
            "Write one short sentence using each phrase",
          ],
        },
      },
      {
        event_id: "run-plan",
        event_name: "Running",
        plugin: "running",
        task: {
          type: dayIndex === 1 ? "intervals" : "easy_run",
          workout: dailyVariants.running[dayIndex],
          notes: ["Keep pace conversational", "Finish with 3 strides"],
          session_plan: [
            "Warmup jog 5 minutes",
            dayIndex === 1 ? "Main set: 6 x 2 minutes fast / 2 minutes easy" : "Main set: steady run",
            dayIndex === 1 ? "Cool down jog 8 minutes" : "Cool down jog 5 minutes",
            "Post-run: 3 x 15-second strides",
            "Hydrate and log RPE (1-10)",
          ],
        },
      },
      {
        event_id: "stretch-night",
        event_name: "Stretching",
        plugin: "stretching",
        task: {
          type: "mobility",
          summary: dailyVariants.stretching[dayIndex],
          notes: ["2 rounds: hips, hamstrings, thoracic spine"],
          session_plan: [
            "Box breathing 90 seconds",
            "Hip opener flow 3 minutes",
            "Hamstring mobility 3 minutes",
            "Thoracic spine rotation 3 minutes",
            "Shoulder opener + neck release 2 minutes",
          ],
        },
      },
    ],
  };
}

export function getMockTasksForDate(date: Date): TodayTask[] {
  return mapTodayResponseToTasks(getMockTodayResponseForDate(date));
}
